services:
  workspace:
    image: phillarmonic/frankenphp-workspace:1.5-php-8.3
    platform: linux/amd64
    environment:
      PROJECT_ROOT: ${PROJECT_ROOT:-/var/www/html}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT:-/var/www/html/public}
      XDEBUG_ENABLE: 0
      XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug,profile,coverage}
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-yes}
      PHP_IDE_CONFIG: serverName=frankenphp
      PHP_INI_ERROR_REPORTING: ${PHP_INI_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED}
      # If you're using the local multi domain https feature, set the vhost here
      # More info at https://github.com/Phillarmonic/domainpilot
      DOMAINPILOT_VHOST: products.docker.local
    volumes:
      - ${HOST_SOURCE_FOLDER:-./code}:${PROJECT_ROOT:-/var/www/html}
      # Certificates and other Caddy data
      - caddy_data:/data
      - ~/.ssh/:/home/docker/.ssh/:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - domainpilot-proxy

  syncopatedb:
    image: phillarmonic/syncopatedb:latest
    ports:
      - "9080:8080"
    volumes:
      - sdb-data:/data
    networks:
      - default

volumes:
  caddy_data:
    driver: local
  sdb-data:
    driver: local

networks:
    domainpilot-proxy:
        external: true